//created on: Dec 10, 2018
package rs.devoteam.cashflow

rule "Decrease balance for debits"
	agenda-group "calculation"
	ruleflow-group "calculation"
    when
        $ap : AccountPeriod()
        $acc : Account( $accountNo : accountNo )
        CashFlow( 	type == "DEBIT",
        			accountNo == $accountNo,
        			date >= $ap.start && <= $ap.end,
        			$amount : amount )
    then
        $acc.setBalance($acc.getBalance() - $amount);
		System.out.println("Balance decreased for " + $amount + ", current amount: " + $acc.getBalance());
end

